name: Pipeline

on: [push]

env:
  ARTIFACT_NAME:  hello

jobs:
  Test:
    name: Create a python program
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
    - uses: actions/checkout@v2
    
    - name: Hello World
      run: python hello.py

  Build:
    needs: [Test]
    name: Create artifact
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
    - uses: actions/checkout@v2
    
    - name: Upload ${{ env.ARTIFACT_NAME }}
      uses: actions/upload-artifact@v1.0.0 
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./${{ env.ARTIFACT_NAME }}.py
    
    
  
